#### CSCE 489 :: Data Science and Analytics :: Texas A&M University :: Fall 2016

# Eric Chung, Jacob Stafford, Kyle Preston, Stephen Brownlee
# Group Project: Analyzing Stack Over Flow Question

## Overview
- Clean and extract data
- Analyze Data
- Draw Interesting Information
- Make Conclusions 

Data was found at:
    https://www.kaggle.com/stackoverflow/pythonquestions

Useful website: https://www.kaggle.com/jiashenliu/d/stackoverflow/pythonquestions/if-we-treat-stack-overflow-as-a-social-network

## Things to address 
- How will we group the data

### Notes: 
- Need to group data by users, this will allow us to see if a user has a significant role is answer qualitiy
- Get rid of answers that are below a certain threshold 
- See if the score is a better indicator (over word count)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import json
import numpy as np

answers = pd.read_csv('./answers.csv', encoding = 'iso-8859-1')
questions = pd.read_csv('./questions.csv', encoding = 'iso-8859-1')

answers['Length'] = answers.Body.str.len()
questions['Length'] = questions.Body.str.len()

answers.head()

,Id,OwnerUserId,CreationDate,ParentId,Score,IsAcceptedAnswer,Body,Length
0,79741,3259.0,2008-09-17T03:43:22Z,79709,-1,False,<p>It's tough to say definitively without know...,328
1,79768,6043.0,2008-09-17T03:48:29Z,79709,5,False,<p>use variables in the outer function instead...,430
2,79779,8002.0,2008-09-17T03:49:36Z,79709,0,False,<p>Third approach: inner function returns a re...,341
3,79788,NaN,2008-09-17T03:51:30Z,79709,3,False,<p>It's not going to make much difference to m...,739
4,79827,14257.0,2008-09-17T03:58:26Z,79709,1,False,"<p>I'm not sure I understand the question, but...",1054

## Simple Word Count Test

In [2]:
#Filtering the answers, in which all of the tags are removed
answers['Filtered'] = answers.Body.str.strip().str.lower().str.replace('<p>', ' ').str.replace('</p>', ' ').str.replace('<code>', ' ').str.replace('</code>', ' ').str.replace('<blockquote>', ' ').str.replace('</blockquote>', ' ').str.replace('<pre>', ' ').str.replace('</pre>', ' ').str.replace('\n', ' ')
#Getting the length of the new filtered answers
answers['Length_Filtered'] = answers.Filtered.str.len()
answers.head()

,Id,OwnerUserId,CreationDate,ParentId,Score,IsAcceptedAnswer,Body,Length,Filtered,Length_Filtered
0,79741,3259.0,2008-09-17T03:43:22Z,79709,-1,False,<p>It's tough to say definitively without know...,328,it's tough to say definitively without knowin...,322
1,79768,6043.0,2008-09-17T03:48:29Z,79709,5,False,<p>use variables in the outer function instead...,430,use variables in the outer function instead o...,419
2,79779,8002.0,2008-09-17T03:49:36Z,79709,0,False,<p>Third approach: inner function returns a re...,341,third approach: inner function returns a refe...,330
3,79788,NaN,2008-09-17T03:51:30Z,79709,3,False,<p>It's not going to make much difference to m...,739,it's not going to make much difference to mem...,718
4,79827,14257.0,2008-09-17T03:58:26Z,79709,1,False,"<p>I'm not sure I understand the question, but...",1054,"i'm not sure i understand the question, but i...",1008

In [3]:
#Filtering the questions, in which all of the tags are removed
questions['Filtered'] = questions.Body.str.strip().str.lower().str.replace('<p>', ' ').str.replace('</p>', ' ').str.replace('<code>', ' ').str.replace('</code>', ' ').str.replace('<blockquote>', ' ').str.replace('</blockquote>', ' ').str.replace('<pre>', ' ').str.replace('</pre>', ' ').str.replace('\n', ' ')
#Getting the length of the new filtered questions
questions['Length_Filtered'] = questions.Filtered.str.len()
print len(questions.Body)
questions.head()

147075

,Id,OwnerUserId,CreationDate,Score,Title,Body,Length,Filtered,Length_Filtered
0,77434,14008.0,2008-09-16T21:40:29Z,134,How to access the last value in a vector?,<p>Suppose I have a vector that is nested in a...,405,suppose i have a vector that is nested in a d...,327
1,79709,NaN,2008-09-17T03:39:16Z,1,Worse sin: side effects or passing massive obj...,<p>I have a function inside a loop inside a fu...,1102,i have a function inside a loop inside a func...,1066
2,95007,15842.0,2008-09-18T17:59:19Z,48,Explain the quantile() function in R,<p>I've been mystified by the R quantile funct...,1919,i've been mystified by the r quantile functio...,1746
3,103312,NaN,2008-09-19T16:09:26Z,4,How to test for the EOF flag in R?,<p>How can I test for the <code>EOF</code> fla...,183,how can i test for the eof flag in r? f...,141
4,255697,1941213.0,2008-11-01T15:48:30Z,3,Is there an R package for learning a Dirichlet...,<p>I'm looking for a an <code>R</code> package...,485,i'm looking for a an r package which can be...,457

In [6]:
split_q = np.split(questions, 3)
print len(split_q[1])
print len(split_q[0])
print len(split_q[2])

test_q = split_q[0]
train_q = split_q[1]

49025
49025
49025

In [7]:
split_a = np.split(answers, 2)
print len(split_a[1])
print len(split_a[0])

train_a = split_a[0]
test_a = split_a[1]

99296
99296

Does length correspond to how likely a question is to being accepted? Below we test different classifiers to find out. And as it turns out, the answer is, only somewhat (score ~= 0.56).

In [8]:
x_train = train_a[['Length_Filtered']]
y_train = train_a[['IsAcceptedAnswer']]
x_test = test_a[['Length_Filtered']]
y_test = test_a[['IsAcceptedAnswer']]

In [9]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(x_train, y_train)
#Outputting training and testing data for word count of answers
print 'Training accuracy: ',clf.score(x_train,y_train)
print 'Testing accuracy: ',clf.score(x_test, y_test)

C:\Users\s\Anaconda2\envs\cs489\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Training accuracy:  0.554272075411
Testing accuracy:  0.562902835965

In [10]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(x_train, y_train)
print 'Training accuracy: ',clf.score(x_train,y_train)
print 'Testing accuracy: ',clf.score(x_test, y_test)

Training accuracy:  0.595200209475
Testing accuracy:  0.558461569449

In [13]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(x_train, y_train)
print 'Training accuracy: ',clf.score(x_train,y_train)
print 'Testing accuracy: ',clf.score(x_test, y_test)

C:\Users\s\Anaconda2\envs\cs489\lib\site-packages\ipykernel\__main__.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  app.launch_new_instance()

Training accuracy:  0.269477118917
Testing accuracy:  0.261984369965

What about the length of an answer's relationship to that answer's score? Turns out, score is only about half as correlated to length as an answer being accepted or not is (score ~=0.27).

In [14]:
x_train = train_a[['Length_Filtered']]
y_train = train_a[['Score']]
x_test = test_a[['Length_Filtered']]
y_test = test_a[['Score']]

In [15]:
clf = tree.DecisionTreeClassifier()
clf.fit(x_train, y_train)
print 'Training accuracy: ',clf.score(x_train,y_train)
print 'Testing accuracy: ',clf.score(x_test, y_test)

Training accuracy:  0.272669593941
Testing accuracy:  0.272135836287

In [16]:
clf = MultinomialNB()
clf.fit(x_train, y_train)
print 'Training accuracy: ',clf.score(x_train,y_train)
print 'Testing accuracy: ',clf.score(x_test, y_test)

Training accuracy:  0.230039477925
Testing accuracy:  0.289306719304

What about the relationship between the words used and the score of an answer or its likelihood of being accepted?

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
tf_vectorizer = CountVectorizer()

#take the first k answers
k = 1000
answer_text = answers['Filtered'][:k]
#TODO: break these up into multiple kFolds since the data is too large to do in one go
tf_train = tf_vectorizer.fit_transform(answer_text)
#print tf_train
tf_test = tf_vectorizer.transform(answer_text)
        
#print is_accepted_numeric
target = answers['IsAcceptedAnswer'][:k]
#print target

clf = MultinomialNB()
clf.fit(tf_train, target)
print 'Answer Text -> IsAcceptedAnswer MultinomialNB Score: ',clf.score(tf_test, target)

clf = RandomForestClassifier()
clf.fit(tf_train, target)
print 'Answer Text -> IsAcceptedAnswer RandomForest score: ',clf.score(tf_test, target)

clf = tree.DecisionTreeClassifier()
clf.fit(tf_train, target)
print 'Answer Text -> IsAcceptedAnswer DecisionTree score: ',clf.score(tf_test, target)

target = answers['Score'][:k]

clf = MultinomialNB()
clf.fit(tf_train, target)
print 'Answer Text -> Score MultinomialBB score: ',clf.score(tf_test, target)

clf = RandomForestClassifier()
clf.fit(tf_train, target)
print 'Answer Text -> Score RandomForest score: ',clf.score(tf_test, target)

clf = tree.DecisionTreeClassifier()
clf.fit(tf_train, target)
print 'Answer Text -> Score DecisionTree score: ',clf.score(tf_test, target)

Answer Text -> IsAcceptedAnswer MultinomialNB Score:  0.884
Answer Text -> IsAcceptedAnswer RandomForest score:  0.963
Answer Text -> IsAcceptedAnswer DecisionTree score:  1.0
Answer Text -> Score MultinomialBB score:  0.565
Answer Text -> Score RandomForest score:  0.991
Answer Text -> Score DecisionTree score:  1.0

These numbers are surprisingly high! Is our model really that good, or is something wrong? Let's try using values that we suspect should not be related to IsAcceptedAnswer and see what score we get:

In [42]:
target = answers['Id'][:k]

clf = MultinomialNB()
clf.fit(tf_train, target)
print 'Answer Text -> Id MultinomialBB score: ',clf.score(tf_test, target)

clf = RandomForestClassifier()
clf.fit(tf_train, target)
print 'Answer Text -> Id RandomForest score: ',clf.score(tf_test, target)

clf = tree.DecisionTreeClassifier()
clf.fit(tf_train, target)
print 'Answer Text -> Id DecisionTree score: ',clf.score(tf_test, target)

target = answers['Length_Filtered'][:k]

clf = MultinomialNB()
clf.fit(tf_train, target)
print 'Answer Text -> LengthF MultinomialBB score: ',clf.score(tf_test, target)

clf = RandomForestClassifier()
clf.fit(tf_train, target)
print 'Answer Text -> LengthF RandomForest score: ',clf.score(tf_test, target)

clf = tree.DecisionTreeClassifier()
clf.fit(tf_train, target)
print 'Answer Text -> LengthF DecisionTree score: ',clf.score(tf_test, target)

Answer Text -> Id MultinomialBB score:  0.552
Answer Text -> Id RandomForest score:  0.996
Answer Text -> Id DecisionTree score:  1.0
Answer Text -> LengthF MultinomialBB score:  0.634
Answer Text -> LengthF RandomForest score:  0.994
Answer Text -> LengthF DecisionTree score:  1.0

Why would there be a 0.999 score between our bag of words and Id and or Length? Is something in RandomForest and DecisionTrees giving us false positives? Let's see how other classifiers fare when used with Score and IsAcceptedAnswer features.

In [50]:
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import NearestCentroid

clf = MultinomialNB()
clf2 = SVC()
clf3 = LogisticRegression()
clf4 = NearestCentroid()
clf5 = SVR()

print ("Scores for words -> 'Score' ")


def fit_and_score(clf, train, test, target):
    clf.fit(train, target)
    print clf.score(test, target), "\n"

target = answers['Score'][:k]

print("MultinomialNB")
fit_and_score(clf, tf_train, tf_test, target)

print("Support vector classifier")
fit_and_score(clf2, tf_train, tf_test, target)

print("Logistic regression")
fit_and_score(clf3, tf_train, tf_test, target)

print("Nearest centroid")
fit_and_score(clf4, tf_train, tf_test, target)

print("SVR")
fit_and_score(clf5, tf_train, tf_test, target)

Scores for words -> 'Score'
MultinomialNB
0.565

Support vector classifier
0.136

Logistic regression
0.998

Nearest centroid
0.289

SVR
-0.0361438614245

In [51]:

target = answers['IsAcceptedAnswer'][:k]

print ("Scores for words -> 'IsAcceptedAnswer' ")

print("MultinomialNB")
fit_and_score(clf, tf_train, tf_test, target)

print("Support vector classifier")
fit_and_score(clf2, tf_train, tf_test, target)

print("Logistic regression")
fit_and_score(clf3, tf_train, tf_test, target)

print("Nearest centroid")
fit_and_score(clf4, tf_train, tf_test, target)

print("SVR")
fit_and_score(clf5, tf_train, tf_test, target)

Scores for words -> 'IsAcceptedAnswer'
MultinomialNB
0.884

Support vector classifier
0.709

Logistic regression
0.994

Nearest centroid
0.633

SVR
-0.0338116930185

Looks like at least some other classifiers also give near-perfect scores for our word vector's correlation to other features, but at least multiple others don't. Let's assume the classifiers not giving values >.95 are giving us the correct picture.

<b>Scaling Score</b>

Now, let's try to improve these classifiers' scores. First, we try alternate ways of defining 'Score.'  What if we sort score values into 5 custom-defined buckets?

In [49]:
score_scaled = []
for answer in answers['Score']:
    if (answer<0):
        score_scaled.append(0)
    elif (answer < 1):
        score_scaled.append(1)
    elif (answer < 5):
        score_scaled.append(2)
    elif (answer < 15):
        score_scaled.append(3)
    else:
        score_scaled.append(4)
        
target = score_scaled[:k]

print("MultinomialNB")
fit_and_score(clf, tf_train, tf_test, target)

print("Support vector classifier")
fit_and_score(clf2, tf_train, tf_test, target)

print("Logistic regression")
fit_and_score(clf3, tf_train, tf_test, target)

print("Nearest centroid")
fit_and_score(clf4, tf_train, tf_test, target)

print("SVR")
fit_and_score(clf5, tf_train, tf_test, target)

MultinomialNB
0.841

Support vector classifier
0.43

Logistic regression
0.998

Nearest centroid
0.266

SVR
0.0279552547551

Above, we can see this technique was a successful strategy to improve our score for all classifiers except Nearest Centroid, which became slightly worse. SVR seems overall unusable.

### Grouping the data by user ID

In [8]:
question_ids = questions['OwnerUserId'].unique()
answer_ids = answers['OwnerUserId'].unique()

combined_id=set(question_ids).intersection(answer_ids)
print 'So we have '+str(len(combined_id))+' users that post both questions and answers on StackOverFlow'

So we have 11194 users that post both questions and answers on StackOverFlow

In [20]:
users=pd.DataFrame({'idUser':list(combined_id)})
users.head(20)

users['Quantity']=users['idUser'].apply(lambda x: len(questions[questions['OwnerUserId']==x]['Body'])+len(answers[answers['OwnerUserId']==x]['Body']))
users=users.sort(['Quantity'],ascending=0).reset_index(drop=True)
users.head(8)

/Users/kylepreston/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:5: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

      idUser  Quantity
0  1855677.0      4997
1  1270695.0      2643
2  2372064.0      2314
3   143305.0      2245
4  1838509.0      2201
5  1412059.0      1895
6   190277.0      1838
7  3063910.0      1665

In [22]:
Q_data=questions[['OwnerUserId','Body']]
A_data=answers[['OwnerUserId','Body']]
question=Q_data[Q_data['OwnerUserId'].isin(users)]
answer=A_data[A_data['OwnerUserId'].isin(users)]

In [23]:
#Showing an example of how we can inspect a specific user by their ID
highest = answers.loc[answers['OwnerUserId'] == 1855677.0]
highest.head(500)

,Id,OwnerUserId,CreationDate,ParentId,Score,IsAcceptedAnswer,Body,Length,Filtered,Length_Filtered
568,1430603,1855677.0,2009-09-16T02:20:17Z,1428750,2,False,<p>?break</p>\n\n<p>Only gets you out of loop....,131,?break only gets you out of loop. ?try ...,110
748,1534985,1855677.0,2009-10-08T00:30:53Z,1529559,1,False,<pre><code> b&lt;-(y!=0)+0\n\n&gt; b\n [1] 0 1...,78,b&lt;-(y!=0)+0 &gt; b [1] 0 1 1 1 0 0 1 1...,57
749,1535082,1855677.0,2009-10-08T01:09:15Z,1523126,5,False,"<p>""Preprocess"" in R:</p>\n\n<pre><code>lines ...",863,"""preprocess"" in r: lines &lt;- ""www, rrr,...",775
1851,2483544,1855677.0,2010-03-20T15:15:12Z,2464680,1,False,"<p>The ""chi-square test"" is usually generated ...",619,"the ""chi-square test"" is usually generated as...",568
1852,2483836,1855677.0,2010-03-20T16:39:14Z,2478272,15,True,<p>One other approach besides kruskal::agricol...,2196,one other approach besides kruskal::agricolae...,2095
1853,2485519,1855677.0,2010-03-21T01:45:10Z,2480984,2,False,<p>You should send the question to Martin Maec...,279,you should send the question to martin maechl...,273
1854,2485556,1855677.0,2010-03-21T02:00:30Z,2458013,26,False,<pre><code>&gt; body(foo)[[3]] &lt;- substitut...,275,&gt; body(foo)[[3]] &lt;- substitute(line2 &...,249
2964,3223529,1855677.0,2010-07-11T15:16:22Z,3223303,4,False,<p>You really do not want to use a matrix for ...,914,you really do not want to use a matrix for th...,888
3833,3596420,1855677.0,2010-08-29T20:16:19Z,3590045,2,True,<p>Here's a complete solution that combines th...,1137,here's a complete solution that combines the ...,1056
4759,4036593,1855677.0,2010-10-27T18:49:28Z,4016144,1,False,"<p>Spacedman doesn't do lattice, but it seems ...",213,"spacedman doesn't do lattice, but it seems fa...",187
4822,4065153,1855677.0,2010-10-31T21:12:19Z,4064464,0,False,<p>I'm sure a gsubfn wizard could do this bett...,1140,i'm sure a gsubfn wizard could do this better...,1028
4830,4069316,1855677.0,2010-11-01T13:34:18Z,4058145,3,False,"<p>There is an article by Duncan Temple Lang, ...",528,"there is an article by duncan temple lang, ar...",517
4833,4072094,1855677.0,2010-11-01T18:52:25Z,4070698,-1,False,"<p>Not sure what you mean by the ""8 default ru...",648,"not sure what you mean by the ""8 default rule...",642
4835,4072402,1855677.0,2010-11-01T19:29:39Z,4047188,3,False,<p>Couldn't find it in that location on my mak...,899,couldn't find it in that location on my make ...,878
4843,4074397,1855677.0,2010-11-02T01:52:19Z,4074179,3,True,"<p>If you take out the regions=names(choro), ...",626,"if you take out the regions=names(choro), yo...",595
4854,4080503,1855677.0,2010-11-02T17:41:32Z,4075983,3,False,"<p>Try this:</p>\n\n<pre><code>yacas( ""OldSolv...",88,"try this: yacas( ""oldsolve({a*x+y==0,x+z=...",62
4860,4082589,1855677.0,2010-11-02T22:17:03Z,4081973,2,False,<p>Read only the one column and what I am assu...,384,read only the one column and what i am assumi...,358
4885,4097251,1855677.0,2010-11-04T13:45:00Z,4096805,3,False,<p>Try</p>\n\n<pre><code> myfunction &lt;- f...,511,try myfunction &lt;- function(datafram...,460
4941,4117936,1855677.0,2010-11-07T13:35:45Z,4115433,2,False,<p>Terry Therneau answered this on rhelp earli...,4305,terry therneau answered this on rhelp earlier...,4274
4943,4119779,1855677.0,2010-11-07T21:25:12Z,4118900,1,False,<p>I agree with PaulHurleyuk that your questio...,785,i agree with paulhurleyuk that your question ...,734
4944,4119933,1855677.0,2010-11-07T22:00:36Z,4115071,3,False,<p>If you assume that Party is always the same...,1561,"if you assume that party is always the same, ...",1482
4948,4121455,1855677.0,2010-11-08T05:17:19Z,4121291,7,True,<p>A couple of possibilities. First with the i...,418,a couple of possibilities. first with the ife...,362
4953,4124762,1855677.0,2010-11-08T14:31:06Z,4121062,3,True,<p>The key here is to forget about ylim when u...,378,the key here is to forget about ylim when usi...,347
4962,4126475,1855677.0,2010-11-08T17:50:38Z,4126326,37,True,<p>The method I use is one of these or <code>H...,1244,the method i use is one of these or hmisc::c...,1110
4970,4130345,1855677.0,2010-11-09T03:46:47Z,4130059,1,True,<p>R is a functional programming language. tkp...,670,r is a functional programming language. tkplo...,619
4995,4140546,1855677.0,2010-11-10T01:48:20Z,4140371,2,False,<p>First a bit of R notation. The If you look ...,779,first a bit of r notation. the if you look at...,748
5021,4157307,1855677.0,2010-11-11T17:29:36Z,4147961,1,False,<p>I don't see that capability in the rpanel f...,439,i don't see that capability in the rpanel fun...,433
5029,4160540,1855677.0,2010-11-12T00:17:46Z,4159517,3,False,<p>The average number of posts per second is j...,570,the average number of posts per second is jus...,539
5042,4167749,1855677.0,2010-11-12T18:16:39Z,4167434,1,False,<p>I don't see that I have the capacity to edi...,405,i don't see that i have the capacity to edit ...,394
5048,4173296,1855677.0,2010-11-13T15:39:32Z,4173019,4,True,<p>Have you installed and loaded the RSQLite.e...,373,have you installed and loaded the rsqlite.ext...,342
...,...,...,...,...,...,...,...,...,...,...
12706,7455948,1855677.0,2011-09-17T15:44:50Z,7455768,1,True,<p>You should be able to use the output of ano...,577,you should be able to use the output of anova...,555
12708,7456471,1855677.0,2011-09-17T17:10:43Z,7454454,1,True,"<p>I think you should use the term ""vector"" wh...",930,"i think you should use the term ""vector"" whic...",904
12713,7457708,1855677.0,2011-09-17T20:52:51Z,7456752,0,True,<p>I think you need to move the tagging operat...,727,i think you need to move the tagging operatio...,701
12721,7458997,1855677.0,2011-09-18T01:46:16Z,7458796,1,False,"<p>As they say on TV ""Had this been a real war...",635,"as they say on tv ""had this been a real warni...",579
12724,7459345,1855677.0,2011-09-18T03:42:47Z,7459138,2,False,<p>Since you want similarities but did not spe...,262,since you want similarities but did not speci...,220
12735,7463335,1855677.0,2011-09-18T18:05:43Z,7463273,2,False,<p>You are proposing making B a function of A ...,219,you are proposing making b a function of a (a...,193
12746,7466939,1855677.0,2011-09-19T05:53:12Z,7466388,8,False,<p>At one time you needed to use <code>setClas...,318,at one time you needed to use setclassunion(...,301
12754,7471977,1855677.0,2011-09-19T13:47:40Z,7471243,2,True,<p>I do not believe you could have used that i...,893,i do not believe you could have used that inp...,856
12757,7473633,1855677.0,2011-09-19T15:47:48Z,7473067,2,False,<p>You probably need to be doing this with R 2...,337,you probably need to be doing this with r 2.1...,331
12758,7473668,1855677.0,2011-09-19T15:49:40Z,7472466,1,True,<p>Something along the lines of this would giv...,589,something along the lines of this would give ...,538
12761,7474537,1855677.0,2011-09-19T16:57:19Z,7474494,3,True,"<p>It doesn't work because the ""$"" operator do...",551,"it doesn't work because the ""$"" operator does...",514
12773,7476024,1855677.0,2011-09-19T19:08:30Z,7474943,0,False,<p>When a somewhat similar question about a cu...,711,when a somewhat similar question about a cumu...,660
12778,7478909,1855677.0,2011-09-20T00:40:10Z,7478837,5,True,"<p>There are two methods that would ""add or ap...",626,"there are two methods that would ""add or appe...",528
12820,7492337,1855677.0,2011-09-20T22:04:05Z,7492247,17,True,"<pre><code>&gt; difftime(dt[2], dt[1], units=""...",94,"&gt; difftime(dt[2], dt[1], units=""secs"") ti...",73
12828,7494895,1855677.0,2011-09-21T05:15:59Z,7494416,2,False,"<p>You said ""attributes"" by which I assumed yo...",742,"you said ""attributes"" by which i assumed you ...",720
12851,7502983,1855677.0,2011-09-21T16:03:54Z,7497802,3,True,<p>I do not see any problem so far. I get a si...,885,i do not see any problem so far. i get a simi...,834
12863,7506112,1855677.0,2011-09-21T20:20:09Z,7505547,7,False,<p>Building on Gavin's answer but not quite to...,966,building on gavin's answer but not quite to a...,940
12870,7508456,1855677.0,2011-09-22T01:11:30Z,7507765,4,False,<p>You cannot mix numeric and alpha in a matri...,419,"you cannot mix numeric and alpha in a matrix,...",393
12877,7509214,1855677.0,2011-09-22T03:24:23Z,7509067,2,True,<p>I do not see any levels arguments in ggplot...,692,i do not see any levels arguments in ggplot a...,639
12889,7515702,1855677.0,2011-09-22T13:41:00Z,7512472,2,False,<p>Those synonyms are in a form that looks lik...,1320,those synonyms are in a form that looks like ...,1236
12891,7515863,1855677.0,2011-09-22T13:51:16Z,7515377,4,False,<p>The <code>order</code> function will allow ...,686,the order function will allow you to determ...,649
12893,7515974,1855677.0,2011-09-22T13:58:20Z,7515419,1,True,"<p>I was going to say ""Use <code>cex.axis</cod...",954,"i was going to say ""use cex.axis to make th...",887
12933,7529659,1855677.0,2011-09-23T13:26:06Z,7528571,2,False,<p>You are almost all the way there. All you n...,2247,you are almost all the way there. all you nee...,2141
12934,7529800,1855677.0,2011-09-23T13:35:54Z,7525226,0,True,<p>I am guessing it's a timezone problem. What...,2386,i am guessing it's a timezone problem. what h...,2255
12943,7532199,1855677.0,2011-09-23T16:37:14Z,7532064,3,True,"<p>There's no ""i"" inside that first version of...",949,"there's no ""i"" inside that first version of ""...",876
12951,7534080,1855677.0,2011-09-23T19:50:58Z,7532639,0,False,<p>Here's another version that removes all inf...,221,here's another version that removes all infin...,195
12952,7534279,1855677.0,2011-09-23T20:10:27Z,7532497,1,False,<p>The xtabs function returns a contingency ta...,472,the xtabs function returns a contingency tabl...,441
12953,7534474,1855677.0,2011-09-23T20:30:13Z,7534328,1,True,<pre><code>xtabs(data=dat)\n Product\nSu...,818,xtabs(data=dat) product subject proda...,742
12955,7534548,1855677.0,2011-09-23T20:38:40Z,7534466,12,True,<p>You said you just wanted the column x value...,995,you said you just wanted the column x values ...,919
12956,7534640,1855677.0,2011-09-23T20:45:15Z,7534181,3,True,<p>@Dirk Eddelbeuttel has posted a bunch of st...,784,@dirk eddelbeuttel has posted a bunch of stuf...,773

In [24]:
combined_questions=[]
combined_answers=[]
user_ids=list(users['idUser'])
for id in user_ids:
    Q_frame=questions[questions['OwnerUserId']==id].reset_index(drop=True)
    A_frame=answers[answers['OwnerUserId']==id].reset_index(drop=True)
    for i in range(len(Q_frame['OwnerUserId'])):
        if i==0:
            tmp=Q_frame['Filtered'][i]
        else:
            tmp=tmp+Q_frame['Filtered'][i]
    combined_questions.append(tmp)
    
    for j in range(len(A_frame['OwnerUserId'])):
        if j==0:
            tmp2=A_frame['Filtered'][j]
        else:
            tmp2=tmp2+A_frame['Filtered'][j]
    combined_answers.append(tmp2)

In [25]:
Question_C=[]
Answer_C=[]

for i in range(11194):
    tmp1="".join(combined_questions[i])
    tmp2="".join(combined_answers[i])
    Question_C.append(tmp1)
    Answer_C.append(tmp2)

In [26]:
Final_frame=pd.DataFrame({'User_id':user_ids,'Question':Question_C,'Answer':Answer_C})
Final_frame.head()
series_a = Final_frame.loc[Final_frame['User_id'] == 1855677.0].Answer
string_series = series_a.to_string().replace('   ','')
print string_series

0  ?break only gets you out of loop. ?try ...